### PR TITLE
WIP: Add react-bootstrap. Create NavBar

### PR DESCRIPTION
**Pull request by AmirNaghibi**
- Add [react-bootstrap](https://react-bootstrap.github.io/) dependency
- created simple navbar

TODO:
add some basic paragraph to the homepage, make a link to other pages

will resolve issue #11

### CODE REVIEW

**Review by engichang1467 — CHANGES_REQUESTED** [review]
Please merge with the beta branch instead.
Make sure you merge with beta first b/c I just merge my stuff to beta already (reducing conflict)

**Comment by engichang1467** [comment]
Please merge with the beta branch instead.
Make sure you merge with beta first, and I just merge my stuff to beta already (reducing conflict)

**Comment by AmirNaghibi** [comment]
I have a WIP task which is experimenting with react bootstrap. It's a simple navbar. You can go ahead and merge beta to master.

**Comment by AmirNaghibi** [comment]
The main task is to come up with MVP requirements.

Also, we can start using beta branch when we have a regular dev cycles and have the master branch for production.

For efficiency sake, for smaller and non code changes, merging to master after a PR review is enough.

**Review by engichang1467 — APPROVED** [review]
K then np

**Pull request merged**
